### ISSUE TITLE
Provide feedback on containerization progress.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#1297]
This issue tracks the tasks needed to implement the progress feedback system intended to address issues #1251 and #806.

(# represents the estimated amount of work)

Design:
- [x] (5) Proposal #1262

Core system:
- [x] (2) Add `Progress.Allocation` class to represent the [decentralized allocation tree](https://github.com/GoogleContainerTools/jib/blob/master/proposals/progress_output.md#decentralized-allocation-tree-dat) #1298
- [x] (1) Add `Progress.Event` class to represent a `JibEvent` indicating progress on some `Progress.Allocation` #1305
- [x] (5) Add `ProgressEventHandler` for handling `Progress.Event`s and managing an overall progress amount #1309

Integration:
- [x] (1) Change `StepsRunner` to be more of a builder to prepare for assigning `Allocation`s #1312
- [x] (4) Assign `Progress.Allocation` to each builder step #1321
- [x] (4) Change `RegistryClient` push and pull to take callback to listen on the progress of the push/pull #1323
  - [x] (3) Add `ListenableCountingOutputStream` to count sent/received bytes #1300
- [x] (3) Add `ProgressEventDispatcher` to dispatch `ProgressEvent`s efficiently #1330
- [x] (2) Emit progress of push/pull as `ProgressEvent`s #1334
- [x] (3) Add integration test(s) to make sure progress reaches 100% after each of the builds #1339

Display:
- [x] (3) Add `AnsiLoggerWithFooter` to be able to keep a footer for where progress indication will go #1326
- [x] (3) Add `ProgressDisplayGenerator` to generate the displayed text for progress feedback #1333
- [x] (2) Add `AnsiLoggerWithFooter` to Maven/Gradle #1341
- [x] (2) Change `LogEventHandler` to use `AnsiLoggerWithFooter` #1341
- [x] (3) Add ability to switch on/off the old logging and the footer #1344
- [x] (2) Change `ProgressEventHandler` to provide the callback with updates #1343
- [x] (1) Attach `ProgressEventHandler` as an event handler via the plugins #1350
- [x] (1) Change `jib.showProgress` to `true` by default #1354

Cleanup:
- [x] Refactor progress callbacks in `RegistryClient` classes #1334 
- [x] (2) Improve `AnsiLoggerWithFooter` logic #1340
- [ ] Have [`AllocationCompletionTracker` only give back unfinished leaf allocations](https://github.com/GoogleContainerTools/jib/pull/1333#discussion_r240398273) - #1356
- [ ] See if it's cleaner to have `ProgressLogger` track the unfinished allocations - #1356
- [ ] Make `ProgressEventDispatcher` API clearer (https://github.com/GoogleContainerTools/jib/pull/1330#discussion_r240724667) - #1357
- [x] Reword the task descriptions #1351
- [ ] Refactor out `ProjectProperties#waitForLoggingThread` and `ProjectProperties#getEventHandlers`- #1358

POC code is in https://github.com/GoogleContainerTools/jib/tree/progress-monitor-poc.

Integrations to check (please assign yourself by adding your name after the item):

- [ ] Skaffold output
- [ ] IntelliJ console
- [ ] Eclipse console
- [ ] Windows

**Comment by loosebazooka** [comment]
Can we add some items to check how this works with skaffold/ides (you can assign them to people) and to have a default non-tty progress option (or NoOp)
