### ISSUE TITLE
SyncMap output for Skaffold

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#2097]
Just a tracking bug

- [x] Add json templates (#2051)
- [x] Expose containerizing mode parser (#2098)
- [x] Share skip logic (#2102)
- [x] Fix test project naming (#2103)
- [x] Add intermediate build config api (#2115)
- [x] Fix travis (#2122)
- [x] Add maven goal (#2055)
- [x] Add gradle task (#2149)
