### ISSUE TITLE
[jib-cli] buildfile tracking bug

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#2570]
- [x] Proposal (#2515) 

Parser
- [x] Yaml Parsing Dependencies (#2571)
- [x] PropertiesSpec (#2571)
- [x] CopySpec (#2579)
- [x] LayerSpec, ArchiveLayerSpec, FileLayerSpec (#2580)
- [x] PlatformSpec (#2581) (#2624)
- [x] BaseImageSpec (#2588)
- [x] LayersSpec (#2590)
- [x] BuildFileSpec (#2598) (#2624) 

Processors
- [x] File Permissions Stack (#2645) (#2683)
- [x] LayersSpec -> List<LayerObject> (#2667) (#2700)
- [x] JibContainerBuilder Generator (#2735)

Open Questions?
- [x] Disallow null and empty values on requires parameters (#2606)
- [x] Disallow empty values on optional parameters (#2649)
- [x] Disallow null or empty values in collections (#2649)
- [x] Use of optional in non-api classes (https://github.com/GoogleContainerTools/jib/pull/2581#discussion_r453899698)
- [x] Can we throw subclass of JsonProcessingException? (https://github.com/GoogleContainerTools/jib/pull/2598#discussion_r456577550)
- [x] Empty collections vs Optional. (https://github.com/GoogleContainerTools/jib/pull/2598#discussion_r456577550) (#2609)

Opened some new bugs for any remaining issues
