### ISSUE TITLE
Refactor to reduce duplicate code

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#262]
Refactor to reduce copy/pasted code between the following files:
- [x] `BuildDockerSteps` and `BuildImageSteps` (#309)
- [x] `BuildContainerConfigurationStep` and `BuildTarballLoadDockerStep`/`PushImageStep` (#269)
- [x] `BuildDockerStepsRunner` and `BuildImageStepsRunner` (#289)
- [x] `BuildDockerTask` and `BuildImageTask` (#296)
- [x] `BuildDockerMojo` and `BuildImageMojo` (#299)
- [x] `gradle.ProjectProperties` and `maven.ProjectProperties` (#310)

**Comment by coollog** [comment]
Oh actually, hold off on that for a bit.

**Comment by coollog** [comment]
Gonna do this first: #305

**Comment by TadCordle** [comment]
Cool, if you want to take those you can, I'm working on the two ProjectProperties right now.
