### ISSUE TITLE
Jib CLI Jar Processing Tracking Bug

### ISSUE THREAD

**Issue by mpeddada1** [GoogleContainerTools/jib#2796]
While the jib cli is meant to allow users to containerize any file without having to integrate jib into java build tools (maven and gradle), this particular cli command will be used to **containerize a jar file**.
Specifically:
    - It is aimed at requiring minimal input from users in order to make the jar workable once it is on the image. 
    - It will make inferences about the jar application entrypoint and will optimize the primary jar into either three layers (class 
      files, non *.class files and dependencies) or two layers (jar, dependencies). This will give users the ability to containerize 
      their jar files while still maintaining the original intent of jib in providing granularity.

Rollout Plan: 
- [x] Implement first part of JarProcessor to determine the type of the jar provided.
- [ ] Implement explodedMode for regular jars.
- [ ] Implement packagedMode for regular jars.
- [ ] Implement explodedMode for Spring Boot fat jars.
- [ ] Implement packagedMode for Spring Boot fat jars. 
- [ ] Add other image parameters to JarInfoBuilder.

**Comment by loosebazooka** [comment]
So the more I think about this, the more each of these bugs should be separate and tracked together as a project.

**Comment by mpeddada1** [comment]
That's a nice idea. Closing this tracking bug since [Jib Cli Jar Processing Project](https://github.com/GoogleContainerTools/jib/projects/11) has been created.
