### ISSUE TITLE
Support WARs.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#431]
Thumbs up if you would like Jib to be able to containerize applications normally packaged as WARs.

**Comment by xiangfeid** [comment]
Is there a timeline for this?

**Comment by coollog** [comment]
@xiangfeid We are actively working on this issue and welcome input for solutions from anyone in the community. We expect a solution to be provided by the `0.10.0` version milestone.

@chanseokoh will be able to guide the conversation and design

**Comment by YJFinBJ** [comment]
I have issue in "comand and tomcat war support #646"

**Comment by chanseokoh** [comment]
For documentation after some preliminary research:

`pom.xml` of an example Maven WAR project:
```xml
  <packaging>war</packaging>
  <version>0.1.0-SNAPSHOT</version>

  <groupId>com.example</groupId>
  <artifactId>war-example</artifactId>
```

1. `$ mvn package`
1. ```
   $ cat > target/Dockerfile <<EOF
   FROM gcr.io/distroless/java/jetty:debug

   # By convention, the exploded WAR directory is <artifact-id>-<version>.
   COPY war-example-0.1.0-SNAPSHOT /jetty/webapps/ROOT

   ENTRYPOINT ["java","-jar","/jetty/start.jar"]
   CMD []
   EOF
   ```
1. `$ docker build -t my-app-on-jetty target/`
1. `$ docker run  -p 8080:8080 -t my-app-on-jetty`

The app will be available at `localhost:8080`. I expect the Tomcat base image would not be too different from this flow.

There are other images like the official Jetty Docker image and the [Google-maintained Jetty runtime image](https://github.com/GoogleCloudPlatform/jetty-runtime),  but I think we'll stick to the distroless Jetty. I hope it enabled all the typical web app support like JSP and JSTL.

**Comment by briandealwis** [comment]
So we could put `WEB-INF/classes` in one layer, `WEB-INF/lib` in a second layer, and everything else in a third layer.  Does that make sense?

**Comment by coollog** [comment]
Yep! Should be fairly simple to write an adapter for this war format once #516 is merged.

**Comment by loosebazooka** [comment]
@tofflos, are you wondering about provided deps? We do not include provided deps so if MicroProfile is providing them for you that's fine.

In the case of the app server, you would still pull `payara/micro`. The one issue is determining `$DEPLOY_DIR`, we will have a provision for custom application locations, our default case will probably support distroless/jetty though.

**Comment by joelhandwell** [comment]
[gretty](https://github.com/gretty-gradle-plugin/gretty) is one of widespread gradle plugins for war app development and jib integration would be great.

**Comment by CyrilleH** [comment]
Hello,

I added some [code](https://github.com/CyrilleH/jib/commit/f653a3db113cb3b909ba17b796567899882b6111) to support "exploded" WAR projects with the gradle plugin. 

[Here](https://github.com/CyrilleH/jib/tree/war-support/jib-gradle-plugin#webapp-example-with-apache-tomcat) you will find an example of use.

Maybe it may help...

**Comment by coollog** [comment]
@CyrilleH Thanks for sharing this!

**Comment by chanseokoh** [comment]
Task tracking:

- [x] propagate `WorkingDir` (issue: https://github.com/GoogleContainerTools/jib/issues/595#issuecomment-417104491 / PR: #902)
- [ ] propagate `ExposedPorts` (issue: https://github.com/GoogleContainerTools/jib/issues/595#issuecomment-417128933)
- [ ] propagate `Cmd` and `Entrypoint` (issue: https://github.com/GoogleContainerTools/jib/issues/595#issuecomment-418744421, #924)
- [x] add `ZipUtil` for unzipping WAR (PR: #906, #908)
- [x] support for exploded WAR layer configuration and distroless Jetty default entry (PR: #917)
- [ ] `container.appRoot` for configuring the application root (issue: #964 / PR: #984)
- [ ] fine-grained multiple layers instead of a single exploded WAR layer
- [ ] Gradle WAR support (PR: #923)
- [ ] Maven WAR support
- [ ] inferring `Entrypoint` from base images (Jetty / Tomcat / ? / ... )
- [ ] update docs (including `container.appRoot`)
- [ ] add a WAR example
- [ ] add integration tests

**Comment by coollog** [comment]
Hi everyone, version `0.10.0` has been released with support for WARs!

**Comment by mvysny** [comment]
Hi @coollog thank you very much! Is this feature documented please, or is there an example project for this?
