### ISSUE TITLE
Add ability to configure extra layer with arbitrary files.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#473]
This will help with implementing https://github.com/GoogleContainerTools/jib/blob/more-layers-proposal/proposals/java_agents_and_more_layers.md once that is approved. Probably, for now, we'll just have it as `BuildConfiguration#setExtraFilesLayerConfiguration(LayerConfiguration)`.

Tasks:
- [x] `ReproducibleLayerBuilder` needs to be configured with `extractionPath` for each set of files added. #475
- [x] Add `LayerConfiguration` - built with a set of `sourceFile`, `destinationOnImage`, which represents a layer with those are the `TarArchiveEntry`s. #476
- [x] Add `BuildConfiguration#setExtraFilesLayerConfiguration` #480
- [x] Cache needs to be changed to have each layer be able to take multiple source files and extraction path pairs #508 
- [x] `BuildAndCacheApplicationLayers` needs to build the extra-files layer, and the image should have that layer. #489 
~~- [ ] Add Maven/Gradle configuration.~~
- [x] Add incubating feature to use files in `src/main/jib` as extra layer #562 

Cleanup:
- [x] Consolidate `LayerConfiguration` with `ReproducibleLayerBuilder#LayerEntry` as a `LayerEntry` in package `image` #503
