### ISSUE TITLE
Reorganize caching to be an interface to allow for different implementations.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#637]
This will help:
- Allow for layer up-to-date checking to be different strategies
- Have all layers be independent so no cache data is lost during concurrent executions

The cache implementation will consist of a storage engine and a query system.

Tasks:
- [x] Add design proposal for new cache mechanism. #878
- [x] Create new cache interfaces under a new package `ncache` that will eventually replace the existing `cache` package. #869
- [x] Add default implementations of the new cache interfaces. #874, #896, #879, #989, #901 
  - [x] DefaultCacheWriteEntry #874, #896
  - [x] DefaultCacheReadEntry #874, #896
  - [x] DefaultCacheStorage #879, #898, #901 
- [x] Add a new `ncache.Cache` that provides the higher-level operations used by the builder steps. #975, #1022, #1031, #1037, #1046
- [x] Have the builder steps use the new `ncache.Cache` and compare performance with old `cache.Cache` (performance is basically the same after checking with 100,000+ files)
- [x] Change the builder steps to use the new `ncache.Cache`. #1047
- [x] Remove old `cache` package #1047
- [ ] Move `ncache` to `cache`. #1056
- [ ] Consider adding a cache pruner that deletes all cache entries without a selector.
- [ ] Make sure all issues in #922 are fixed.
- [ ] Explore detections of potential cache corruptions - see #980

**Comment by coollog** [comment]
Closing this in favor of the followup/cleanup tasks: #1056 #922 and #980
