### ISSUE TITLE
Add event system for propagating asynchronous events to user of jib-core.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#714]
- [x] Proposal for eventing system #909 
- [x] Add eventing system #921, #931 
- [x] Define events for each log point
  - [x] Set up and `RetrieveRegistryCredentialsStep` #971
  - [x] Replace all uses of `JibLogger` with emitting `LogEvent`/`TimerEvent` and remove `JibLogger`. #1034, #1043, #1048
- [ ] Rename `EventEmitter` to `EventDispatcher` #1053

Followup:
- Create new events that contain structured information for users of Jib Core for various parts of the build execution

**Comment by coollog** [comment]
@GoogleContainerTools/java-tools It would be good to have someone else take a stab at the rest of the tasks so they can try out using the eventing system API.

**Comment by TadCordle** [comment]
I can try working on this.
